default['commander']['ftp-user'] = ''
default['commander']['ftp-password'] = ''
default['commander']['ftp-host'] = '74.85.3.84'
default['commander']['installer-path'] = 'commander/release_4.2/4.2.3.64287/linux/x86'
default['commander']['installer-file'] = 'ElectricCommander-4.2.3.64287'
default['commander']['installer-user-name'] = 'ec'
default['commander']['installer-user-password'] = 'ececec'